import { createHash } from 'node:crypto';

const SERVICE_WORKER_FILE = 'sw.js';

export function computeVersion(
  entries: ReadonlyArray<{ path: string; content: Uint8Array }>,
): string {
  const hash = createHash('sha256');
  const sorted = [...entries].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  for (const entry of sorted) {
    hash.update(entry.path);
    hash.update('\0');
    hash.update(entry.content);
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 12);
}

/**
 * Source of the service worker: precache every built file on install,
 * drop old caches on activate, and serve same-origin GETs cache-first.
 * Navigation requests that miss the cache get index.html, so the app opens offline.
 */
export function buildServiceWorker(files: readonly string[], version: string): string {
  const precache = files.filter((f) => f !== SERVICE_WORKER_FILE);
  return `// Generated by tools/precache-plugin.ts. Do not edit.
const CACHE = ${JSON.stringify(`boss-trainer-${version}`)};
const FILES = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) =>
        cache.addAll(
          FILES.map((f) => new Request(new URL(f, self.registration.scope).href, { cache: 'reload' })),
        ),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      if (request.mode === 'navigate') {
        return caches.match(new URL('index.html', self.registration.scope).href);
      }
      return fetch(request);
    }),
  );
});
`;
}
